FROM quay.io/bitnami/git:latest

RUN wget https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz && \
    tar -xvf hub-linux-amd64-2.14.2.tgz && \
    ./hub-linux-amd64-2.14.2/install  




