{{- if not .Values.serverless }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.pelorus/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.application_name }}-{{ .Values.environment }}
  annotations:
spec:
  replicas: {{ .Values.replicas }}
  selector:
    deploymentConfig: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      labels:
        application: {{ .Release.Name }}
        deploymentConfig: {{ .Release.Name }}
        app.pelorus/name: {{ .Release.Name }}
      name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          imagePullPolicy: Always
          livenessProbe: 
          readinessProbe: 
          resources: 
{{ .Values.resources | toYaml | indent 12 }}
      terminationGracePeriodSeconds: 75
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Release.Name }}
      from:
        kind: ImageStreamTag
        namespace: {{ .Values.application_name }}-{{ .Values.environment }}
        name: {{ .Values.application_name }}:{{ .Values.application_tag }}
{{- end }}


